services:
  kobopatchgui-tk:
    image: ghcr.io/gioxmama/kobopatchgui:latest
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix    # For GUI (WSLg)
      - ./:/patches               # Only .patch files exchanged here
    stdin_open: true
    tty: true
